fix wrong require
If the ActiveRecord version is 7.1.3.4, it will lead to the loading of the join_association_7_2 module, which will then cause a similar NoMethodError: undefined method 'with_connection' for class Ignore error.